[Metadata]
Name=CpuStaticSettings
Author=Lucky Penny
Information=Static variables for the cpu
License=Creative Commons BY-NC-SA 3.0
Version=0.0.3

[Variables]
CpuOverallDisplayDisabled=0
CpuOverallDisplayClockDisabled=0
CpuOverallDisplayFanDisabled=0
CpuOverallDisplayUsageDisabled=0
CpuOverallDisplayGraphDisabled=0

CpuCoresDisplayDisabled=0
CpuCoresDisplayUsageDisabled=0
CpuCoresDisplayTempDisabled=0
CpuCoresDisplayGraphDisabled=1

; Cpu Clock informations
CpuClockSensorId=0xf0000300
CpuClockInstance=0x0
CpuClockEntryId=0x6000000

; Fan informations
CpuFanSensorId=0xf0ec0101
CpuFanInstance=0x0
CpuFanEntryId=0x3000000

; Temperature informations
CpuTempSensorId=0xf0000400
CpuTempInstance=0x0
