[Metadata]
Name=Controls
Author=Lucky Penny
Information=Meters used in modal windows
License=Creative Commons BY-NC-SA 3.0
Version=0.0.1

[MeterClose]
Meter=String
X=([SkinSizing:W]-10)
Y=10
W=16
H=16
StringAlign=Right
StringStyle=Bold
FontSize=12
SolidColor=250,100,100
FontColor=0,0,0
Text=X
AntiAlias=1
LeftMouseUpAction=[!DeactivateConfig]
DynamicVariables=1
UpdateDivider=-1

[Header]
Meter=Image
X=0
Y=0
W=[SkinSizing:W]
H=([Title:H]+15)
SolidColor=#BackgroundColor#,150
DynamicVariables=1
UpdateDivider=-1
